
// Extensión Paste JSON as Code
// https://pokeapi.co/



// Generated by https://quicktype.io

// FIXME no se que es esto
export interface Pokemon {
    id:                 number;
    name:               string;
    growth_time:        number;
    max_harvest:        number;
    natural_gift_power: number;
    size:               number;
    smoothness:         number;
    soil_dryness:       number;
    firmness:           Firmness;
    flavors:            Flavor[];
    item:               Firmness;
    natural_gift_type:  Firmness;
}

export interface Firmness {
    name: string;
    url:  string;
}

export interface Flavor {
    potency: number;
    flavor:  Firmness;
}
